### ISSUE TITLE
Nft-Qos不支持OpenWrt 18.06.1稳定版？

### ISSUE THREAD

**Issue by ikokang** [rosywrt/nft-qos#2]
kokang@compaq:~/openwrt-18.06.1$ ./scripts/feeds update -a
Updating feed 'packages' from 'https://git.openwrt.org/feed/packages.git^35e0b737ab496f5b51e80079b0d8c9b442e223f5' ...
Create index file './feeds/packages.index' 
Updating feed 'luci' from 'https://git.openwrt.org/project/luci.git^f64b1523447547032d5280fb0bcdde570f2ca913' ...
Create index file './feeds/luci.index' 
Updating feed 'routing' from 'https://git.openwrt.org/feed/routing.git^1b9d1c419f0ecefda51922a7845ab2183d6acd76' ...
Create index file './feeds/routing.index' 
Updating feed 'telephony' from 'https://git.openwrt.org/feed/telephony.git^b9d7b321d15a44c5abb9e5d43a4ec78abfd9031b' ...
Create index file './feeds/telephony.index' 
kokang@compaq:~/openwrt-18.06.1$ ./scripts/feeds install -a
WARNING: Makefile 'package/kokang/nft-qos/Makefile' has a dependency on 'kmod-nft-netdev', which does not exist
Installing all packages from feed packages.
Installing all packages from feed luci.
Installing all packages from feed routing.
Installing all packages from feed telephony.

**Comment by rosysong** [comment]
是的， 目前官方仅支持master分支。  rosywrt/packages有18.06的backport, 你可以参考下。

**Comment by ikokang** [comment]
kokang@compaq:~/rosywrt$ ./scripts/feeds install -a
ERROR: please fix package/feeds/telephony/freeswitch/Makefile - see logs/package/feeds/telephony/freeswitch/dump.txt for details
Collecting package info: done
Installing all packages from feed packages.
Installing all packages from feed luci.
Installing all packages from feed rosy.
Installing all packages from feed routing.
Installing all packages from feed telephony.

git clone -b openwrt-18.06 https://github.com/rosywrt/rosywrt.git 下载这个安装的时候又出现这个错误，之前的稳定版也是有同样的错误。
