### ISSUE TITLE
Priority order is undocumented.

### ISSUE THREAD

**Issue by barberio** [rosywrt/nft-qos#3]
Please document which order precedence the priority numbering works.

Is 1 highest priority or 11 highest priority?

**Comment by rosysong** [comment]
Will document it, thanks for your feedback!

**Comment by rosysong** [comment]
By the way, 1 is the highest! @barberio

**Comment by rosysong** [comment]
Merged upstream, please update your code, thanks! @barberio 
https://github.com/openwrt/packages/pull/8372
